// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: red_chirpy.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const upgradeUserToChirpy = `-- name: UpgradeUserToChirpy :one

UPDATE users
SET is_chirpy_red = true, updated_at = NOW() 
WHERE id = $1
RETURNING id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

func (q *Queries) UpgradeUserToChirpy(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, upgradeUserToChirpy, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}
