// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reset_database.sql

package database

import (
	"context"
)

const resetDatabase = `-- name: ResetDatabase :exec

DELETE from users
`

func (q *Queries) ResetDatabase(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetDatabase)
	return err
}
